[versions]
junit = "6.0.2"
kotlin = "2.3.0"
kotlinx-serialization = "1.10.0"


[libraries]
# org.jetbrains.kotlin - Kotlin
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

# org.junit - JUnit
# https://github.com/junit-team/junit5
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }


# org.jetbrains.kotlinx:kotlinx-serialization-[...] - kotlinx.serialization
# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }


[plugins]
# org.jetbrains.dokka - Dokka Gradle Plugin
# https://github.com/Kotlin/dokka
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }

# org.jetbrains.kotlinx.binary-compatibility-validator - binary-compatibility-validator
# https://github.com/Kotlin/binary-compatibility-validator
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }

# org.jetbrains.kotlin - Kotlin Gradle plugin
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
